---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 6 
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-stunnel
        image: runnable/redis-stunnel
        ports:
        - containerPort: 6380
          name: client
        - containerPort: 16380
          name: gossip
        env:
        ## - name: REDIS_PORT_6379_TCP_ADDR 
        ##   value: "127.0.0.1"
        ## - name: REDIS_PORT_6379_TCP_PORT
        ##   value: "6379"
        volumeMounts:
        - name: stunnel-tls
          mountPath: /etc/stunnel/private.pem
          subPath: rediscert.pem
        - name: stunnel-conf
          mountPath: /etc/stunnel/stunnel.conf
          subPath: stunnel.conf
        - name: stunnel-pid
          mountPath: /stunnel
        command: ["/bin/sh"]
        args: ["-c", "ls -l /etc/stunnel; stunnel4 /etc/stunnel/stunnel.conf"]
      - name: redis
        image: redis:5.0.1-alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
        - name: pod_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: redis-conf
          mountPath: /conf
          readOnly: false
        - name: redis-data
          mountPath: /data
          readOnly: false
      volumes:
      - name: redis-conf
        configMap:
          name: redis
          defaultMode: 0755
      - name: stunnel-tls
        secret:
          secretName: redis
          defaultMode: 0755
      - name: stunnel-conf
        configMap:
          name: stunnel
      - name: stunnel-pid
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
